import type { Category, Enemy } from "./types";

export const ENEMY_CATALOG: Record<Category, Enemy[]> = {
  Mathematics: [
    {
      id: "math-goblin",
      name: "Goblin of Arithmetic",
      title: "Adder of Apples",
      category: "Mathematics",
      emoji: "👺",
      maxHp: 50,
      flavor: "A mischievous sprite who whispers wrong sums in merchants' ears.",
    },
    {
      id: "algebra-wraith",
      name: "Wraith of the Unknown X",
      title: "Solver of Shadows",
      category: "Mathematics",
      emoji: "👻",
      maxHp: 90,
      flavor: "It hides behind variables and reappears when you isolate them.",
    },
    {
      id: "calculus-dragon",
      name: "Dragon of Derivatives",
      title: "The Limit Reaper",
      category: "Mathematics",
      emoji: "🐉",
      maxHp: 140,
      flavor: "Slay it by finding the slope of the present — and the area of the past.",
    },
  ],
  History: [
    {
      id: "history-knight",
      name: "Knight of Eras",
      title: "Defender of Dates",
      category: "History",
      emoji: "🛡️",
      maxHp: 60,
      flavor: "He guards the timeline with a sword forged from footnotes.",
    },
    {
      id: "empire-queen",
      name: "Empress of Empires",
      title: "Crown of Centuries",
      category: "History",
      emoji: "👑",
      maxHp: 100,
      flavor: "She remembers every treaty, every betrayal, every dawn of Rome.",
    },
    {
      id: "time-lich",
      name: "Lich of Lost Centuries",
      title: "Keeper of Chronology",
      category: "History",
      emoji: "💀",
      maxHp: 160,
      flavor: "An immortal scholar whose only weakness is the correct year.",
    },
  ],
  Science: [
    {
      id: "lab-gremlin",
      name: "Gremlin of the Lab",
      title: "Mixer of Mislabeled Beakers",
      category: "Science",
      emoji: "🧪",
      maxHp: 55,
      flavor: "It bubbles at you in periodic table riddles.",
    },
    {
      id: "physics-golem",
      name: "Golem of Gravity",
      title: "Mass × Acceleration",
      category: "Science",
      emoji: "🪨",
      maxHp: 95,
      flavor: "It is 9.81 m/s² of pure menace.",
    },
    {
      id: "biology-mother",
      name: "Matriarch of Mitosis",
      title: "Cell Division",
      category: "Science",
      emoji: "🧬",
      maxHp: 150,
      flavor: "She splits, duplicates, and refuses to be silenced.",
    },
  ],
  Geography: [
    {
      id: "cartographer",
      name: "The Lost Cartographer",
      title: "Mapper of False Shores",
      category: "Geography",
      emoji: "🗺️",
      maxHp: 60,
      flavor: "He trades in capitals that may or may not exist.",
    },
    {
      id: "storm-pirate",
      name: "Pirate of the Pacific",
      title: "Captain of Currents",
      category: "Geography",
      emoji: "🏴‍☠️",
      maxHp: 100,
      flavor: "Crosses only the oceans you can name.",
    },
    {
      id: "mountain-titan",
      name: "Titan of the Himalayas",
      title: "Snow-Line Sentinel",
      category: "Geography",
      emoji: "🏔️",
      maxHp: 160,
      flavor: "He demands you prove you know the altitude.",
    },
  ],
  Literature: [
    {
      id: "bard",
      name: "The Haunted Bard",
      title: "Quoter of Plays",
      category: "Literature",
      emoji: "🎭",
      maxHp: 55,
      flavor: "He tests you with soliloquies and unfinished sentences.",
    },
    {
      id: "novelist-witch",
      name: "Witch of the Novel",
      title: "Chapter and Curse",
      category: "Literature",
      emoji: "📚",
      maxHp: 95,
      flavor: "She conjures plot twists from classic novels.",
    },
    {
      id: "poet-king",
      name: "The Poet-King",
      title: "Rhyme without Reason",
      category: "Literature",
      emoji: "✒️",
      maxHp: 155,
      flavor: "Each verse you answer wrong becomes a wound.",
    },
  ],
  Programming: [
    {
      id: "bug-blob",
      name: "Blob of Bugs",
      title: "Off-by-One",
      category: "Programming",
      emoji: "🐛",
      maxHp: 55,
      flavor: "It multiplies like a stack overflow at midnight.",
    },
    {
      id: "compiler-knight",
      name: "Knight of Compile-Time",
      title: "The Strict Typist",
      category: "Programming",
      emoji: "🧙",
      maxHp: 100,
      flavor: "Refuses to cast your `any` to a sword.",
    },
    {
      id: "recursion-demon",
      name: "Demon of Recursion",
      title: "Base Case Breaker",
      category: "Programming",
      emoji: "🌀",
      maxHp: 165,
      flavor: "It has no base case. Only nested questions.",
    },
  ],
  Music: [
    {
      id: "dissonance",
      name: "Sprite of Dissonance",
      title: "Flat Note Phantom",
      category: "Music",
      emoji: "🎼",
      maxHp: 50,
      flavor: "A whisper in B♭ when you expected B.",
    },
    {
      id: "conductor",
      name: "The Mad Conductor",
      title: "Tempo Tyrant",
      category: "Music",
      emoji: "🎻",
      maxHp: 95,
      flavor: "He tests you on allegro, adagio, and obscure time signatures.",
    },
    {
      id: "mozart-ghost",
      name: "Ghost of the Requiem",
      title: "Counterpoint Collector",
      category: "Music",
      emoji: "👻",
      maxHp: 155,
      flavor: "Only the truly tuned survive his fugue.",
    },
  ],
  Movies: [
    {
      id: "popcorn-goblin",
      name: "Goblin of Popcorn",
      title: "Cinema Fiend",
      category: "Movies",
      emoji: "🍿",
      maxHp: 55,
      flavor: "He strews spoilers like confetti.",
    },
    {
      id: "oscar-ogre",
      name: "Ogre of the Oscars",
      title: "Golden Statue",
      category: "Movies",
      emoji: "🏆",
      maxHp: 100,
      flavor: "He demands you recite every Best Picture since 1970.",
    },
    {
      id: "kaiju",
      name: "Kaiju of the Camera",
      title: "Director's Cut",
      category: "Movies",
      emoji: "🎬",
      maxHp: 160,
      flavor: "A walking film school with teeth.",
    },
  ],
  Sports: [
    {
      id: "referee",
      name: "The Blind Referee",
      title: "Whistle of Misfortune",
      category: "Sports",
      emoji: "🥷",
      maxHp: 55,
      flavor: "Always calls the play against you.",
    },
    {
      id: "olympian",
      name: "Champion of Olympus",
      title: "Gold Medal Ghost",
      category: "Sports",
      emoji: "🏅",
      maxHp: 100,
      flavor: "She has run every marathon and remembers each split time.",
    },
    {
      id: "stadium-titan",
      name: "Titan of the Stadium",
      title: "Roar of 100,000",
      category: "Sports",
      emoji: "🏟️",
      maxHp: 160,
      flavor: "His footstep is a final whistle.",
    },
  ],
  Mythology: [
    {
      id: "harpy",
      name: "Harpy of Olympus",
      title: "Screech of the Fates",
      category: "Mythology",
      emoji: "🦅",
      maxHp: 60,
      flavor: "She knows every name the gods ever cursed.",
    },
    {
      id: "minotaur",
      name: "Minotaur of the Maze",
      title: "Axe of Asterion",
      category: "Mythology",
      emoji: "🐂",
      maxHp: 100,
      flavor: "Only the thread of knowledge leads out.",
    },
    {
      id: "leviathan",
      name: "Leviathan of Lore",
      title: "Serpent of the Deep",
      category: "Mythology",
      emoji: "🐍",
      maxHp: 165,
      flavor: "He has swallowed every pantheon whole.",
    },
  ],
};

export const CATEGORIES = Object.keys(ENEMY_CATALOG) as Category[];

export function pickNextEnemy(
  defeated: number,
  rng: () => number = Math.random
): Enemy {
  const categoryKeys = CATEGORIES;
  const categoryKey =
    categoryKeys[defeated % categoryKeys.length] ?? CATEGORIES[0];
  const tier = Math.min(2, Math.floor(defeated / 3));
  const pool = ENEMY_CATALOG[categoryKey];
  const enemy = pool[Math.min(tier, pool.length - 1)] ?? pool[0];
  const scaledHp = Math.round(enemy.maxHp * (1 + defeated * 0.15));
  return { ...enemy, maxHp: scaledHp };
}